CREATE SCHEMA CSV

CREATE SEQUENCE csvSeq
  INCREMENT 1
  START 1
  MINVALUE 1
  MAXVALUE 1000000000

CREATE TABLE weights(
  STRING_ID BIGINT NOT NULL DEFAULT NEXTVAL('csv.csvSeq'),
  WORD VARCHAR(60),
  STR_VALUE DEC(4,3),
  PRIMARY KEY(STRING_ID)
);