CREATE SCHEMA TIMETABLE

CREATE SEQUENCE timeSeq
  INCREMENT 1
  START 1
  MINVALUE 1
  MAXVALUE 1000000000

CREATE TABLE job(
  ID BIGINT NOT NULL DEFAULT NEXTVAL('timetable.timeSeq'),
  ROOM VARCHAR(100),
  DATE_TIME TIMESTAMP,
  GROUP_NAME VARCHAR(20),
  DISCIPLINE VARCHAR(50),
  PRIMARY KEY(ID)
);


