CREATE SCHEMA CSV

CREATE SEQUENCE csvSeq
  INCREMENT 1
  START 5
  MINVALUE 1
  MAXVALUE 100000000

CREATE TABLE weights(
  STRING_ID INT NOT NULL DEFAULT NEXTVAL('csvSeq'),
  WORD VARCHAR(60) UNIQUE,
  STR_VALUE DEC(4,3),
  PRIMARY KEY(STRING_ID)
);